#!/bin/bash
ps -e | tail +2 | awk '{print $1}' > task4.out
IFS=$'\n'
lines=$(cat task4.out)
lines=($lines)
rm task4.out
for line in "${lines[@]}"
do
	printf $line >> task4.out
	printf ":" >> task4.out
	cat /proc/$line/statm | awk '{print $2-$3}' >> task4.out
done
cat task4.out | tr ":" " " | sort -r -k2 -n | tr ' ' ' : '
unset IFS

