#!/bin/bash
ps -e | tail +2 | awk '{print $1}' > task5.out
IFS=$'\n'
lines=$(cat task5.out)
lines=($lines)
rm task5.out
for line in "${lines[@]}"
do
	printf "ProcessID=" >> task5.out
	cat /proc/$line/status | grep "^Pid" | tr ":" " " | tr $"\t" " " | awk '{printf $2}' >> task5.out
	printf ":Parent_ProcessID=" >> task5.out
        cat /proc/$line/status | grep "^PPid" | tr ":" " " | tr $"\t" " " | awk '{printf $2}' >> task5.out
	printf ":Average_Sleeping_Time=" >> task5.out
        cat /proc/$line/sched | grep "^se.avg.runnable_load_avg" | tr ":" " " | tr $"\t" " " | awk '{print $2}' >> task5.out
done
cat task5.out | tr ":" " " | grep -E "[0-9]+" | sort -V -k2 | tr " " ":" | head -n -1 |
			python3 -c 'for l in __import__("fileinput").input():print(l.replace(":"," : "), end="")' > task5.out
unset IFS
