#!/bin/bash

while true 
do 
	read line
	echo "$line" >> task5_stack_trace
	
	if [[ "$line" == "QUIT" ]]
	then 
		exit 0
	fi

	if [[ ! "$line" =~ [0-9]+ && "$line" != "+" && "$line" != "*" ]] 
	then 
		echo "Incorrect input!"
		exit 1
	fi
done
